### ISSUE TITLE
Barrels, broken calling: java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by Joapple** [John000708/Barrels#2]
[14:20:35 WARN]: [Slimefun] Task #13015361 for Slimefun v4.1.2 generated an exception
java.lang.AbstractMethodError: me.john000708.barrels.Barrel$1$1.onEvent(ILorg/bukkit/inventory/ItemStack;Lorg/bukkit/inventory/ItemStack;)Lorg/bukkit/inventory/ItemStack;
        at me.mrCookieSlime.Slimefun.api.inventory.BlockMenu.replaceExistingItem(BlockMenu.java:113) ~[Slimefun%20v4.1.2.jar:?]
        at me.mrCookieSlime.Slimefun.api.inventory.BlockMenu.replaceExistingItem(BlockMenu.java:106) ~[Slimefun%20v4.1.2.jar:?]
        at me.john000708.barrels.Barrel.pushItems(Barrel.java:452) ~[Barrels_v1.9.jar:?]
        at me.john000708.barrels.Barrel.updateBarrel(Barrel.java:347) ~[Barrels_v1.9.jar:?]
        at me.john000708.barrels.Barrel.access$100(Barrel.java:36) ~[Barrels_v1.9.jar:?]
        at me.john000708.barrels.Barrel$3.tick(Barrel.java:191) ~[Barrels_v1.9.jar:?]
        at me.mrCookieSlime.Slimefun.api.TickerTask$1.run(TickerTask.java:88) ~[Slimefun%20v4.1.2.jar:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.11.2.jar:git-Paper-1057]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.11.2.jar:git-Paper-1057]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:820) [patched_1.11.2.jar:git-Paper-1057]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1057]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [patched_1.11.2.jar:git-Paper-1057]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [patched_1.11.2.jar:git-Paper-1057]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

MC 1.11.2 paperclip
slimefun: 4.1.2
barrels: v1.9

**Comment by Joapple** [comment]
Why closed? Should i post on slimefun even though it's a barrels error...

**Comment by John000708** [comment]
Post it on barrel's forums, is it that confusing?

**Comment by Joapple** [comment]
I did, but thought it was better doing on the github directly like slimefun is doing.. But ya i posted it there.
